// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// **SECURITY:**
/// - Android: API keys are hardcoded in the source code (lines 77-78).
/// - iOS: API keys are loaded from --dart-define flags at build time, with debug fallbacks (lines 98-115).
///
/// Build commands:
/// ```bash
/// # Android
/// flutter build apk --release \
///   --dart-define=ANDROID_API_KEY=your_key \
///   --dart-define=ANDROID_APP_ID=your_app_id \
///   --dart-define=ANDROID_MESSAGING_SENDER_ID=your_sender_id \
///   --dart-define=ANDROID_PROJECT_ID=your_project_id \
///   --dart-define=ANDROID_STORAGE_BUCKET=your_storage_bucket
///
/// # iOS
/// flutter build ios --release \
///   --dart-define=IOS_API_KEY=your_key \
///   --dart-define=IOS_APP_ID=your_app_id \
///   --dart-define=IOS_MESSAGING_SENDER_ID=your_sender_id \
///   --dart-define=IOS_PROJECT_ID=your_project_id \
///   --dart-define=IOS_STORAGE_BUCKET=your_storage_bucket \
///   --dart-define=IOS_BUNDLE_ID=your_bundle_id
/// ```
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: 'AIzaSyDzvTlSYF_BHdMlmbUrqFLxlw-KFM_zIeM',
      appId: '1:1093013909122:android:fc9f8ccf6b26083dc08e9b',
      messagingSenderId: '1093013909122',
      projectId: 'xogame-105c9',
      storageBucket: 'xogame-105c9.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    // All values must be provided via --dart-define (no hardcoded fallbacks for security)
    final apiKey = const String.fromEnvironment('IOS_API_KEY');
    final appId = const String.fromEnvironment('IOS_APP_ID');
    final messagingSenderId = const String.fromEnvironment('IOS_MESSAGING_SENDER_ID');
    final projectId = const String.fromEnvironment('IOS_PROJECT_ID');
    final storageBucket = const String.fromEnvironment('IOS_STORAGE_BUCKET');
    final iosBundleId = const String.fromEnvironment('IOS_BUNDLE_ID');
    
    // Development fallbacks (ONLY for debug builds - removed in release for security)
    // In release builds, all keys must be provided via --dart-define
    const isDebugMode = bool.fromEnvironment('dart.vm.product') == false;
    
    final finalApiKey = apiKey.isEmpty && isDebugMode
        ? 'AIzaSyAJdH5Gv4vxqrvNX0fR6KUeozvQ9LtSGYQ' // Dev fallback
        : apiKey;
    final finalAppId = appId.isEmpty && isDebugMode
        ? '1:209806230058:ios:0240a6709e65f5eea3f953' // Dev fallback
        : appId;
    final finalMessagingSenderId = messagingSenderId.isEmpty && isDebugMode
        ? '209806230058' // Dev fallback
        : messagingSenderId;
    final finalProjectId = projectId.isEmpty && isDebugMode
        ? 'xogame-105c9' // Dev fallback
        : projectId;
    final finalStorageBucket = storageBucket.isEmpty && isDebugMode
        ? 'xogame-105c9.firebasestorage.app' // Dev fallback
        : storageBucket;
    final finalIosBundleId = iosBundleId.isEmpty && isDebugMode
        ? 'com.example.xo' // Dev fallback
        : iosBundleId;
    
    // Validate all required keys are provided (or use dev fallbacks in debug mode)
    if (finalApiKey.isEmpty) {
      throw UnsupportedError(
        'Missing required --dart-define: IOS_API_KEY\n'
        'Build with: flutter build ios --dart-define=IOS_API_KEY=your_key ...\n'
        'See BUILD_INSTRUCTIONS.md for complete build commands.',
      );
    }
    if (finalAppId.isEmpty) {
      throw UnsupportedError(
        'Missing required --dart-define: IOS_APP_ID\n'
        'Build with: flutter build ios --dart-define=IOS_APP_ID=your_app_id ...\n'
        'See BUILD_INSTRUCTIONS.md for complete build commands.',
      );
    }
    if (finalMessagingSenderId.isEmpty) {
      throw UnsupportedError(
        'Missing required --dart-define: IOS_MESSAGING_SENDER_ID\n'
        'Build with: flutter build ios --dart-define=IOS_MESSAGING_SENDER_ID=your_sender_id ...\n'
        'See BUILD_INSTRUCTIONS.md for complete build commands.',
      );
    }
    if (finalProjectId.isEmpty) {
      throw UnsupportedError(
        'Missing required --dart-define: IOS_PROJECT_ID\n'
        'Build with: flutter build ios --dart-define=IOS_PROJECT_ID=your_project_id ...\n'
        'See BUILD_INSTRUCTIONS.md for complete build commands.',
      );
    }
    if (finalStorageBucket.isEmpty) {
      throw UnsupportedError(
        'Missing required --dart-define: IOS_STORAGE_BUCKET\n'
        'Build with: flutter build ios --dart-define=IOS_STORAGE_BUCKET=your_storage_bucket ...\n'
        'See BUILD_INSTRUCTIONS.md for complete build commands.',
      );
    }
    if (finalIosBundleId.isEmpty) {
      throw UnsupportedError(
        'Missing required --dart-define: IOS_BUNDLE_ID\n'
        'Build with: flutter build ios --dart-define=IOS_BUNDLE_ID=your_bundle_id ...\n'
        'See BUILD_INSTRUCTIONS.md for complete build commands.',
      );
    }
    
    return FirebaseOptions(
      apiKey: finalApiKey,
      appId: finalAppId,
      messagingSenderId: finalMessagingSenderId,
      projectId: finalProjectId,
      storageBucket: finalStorageBucket,
      iosBundleId: finalIosBundleId,
    );
  }

}