// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Project: XO Arena Neon Clash
/// Project ID: xo-arenaneon-clash
/// Android package: com.xoarena.neonclash
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'This app is Android-only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'This app is Android-only.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvJUVSC1s_KQEs-NehKmYJ6R3q4ITZqz0',
    appId: '1:928308967161:android:7fab6afb06730609311428',
    messagingSenderId: '928308967161',
    projectId: 'xo-arenaneon-clash',
    storageBucket: 'xo-arenaneon-clash.firebasestorage.app',
  );

}